"""
Generate static HTML pages for GitHub Pages.

This script creates a simple static website in the `_site/` output directory.
Run this script locally or via GitHub Actions to regenerate the site.
"""

import os
from datetime import datetime, timezone

OUTPUT_DIR = "_site"

PAGES = [
    {
        "filename": "index.html",
        "title": "Home",
        "heading": "Welcome to GithubPagesTest",
        "content": (
            "<p>This site is automatically generated by a Python script "
            "and published to GitHub Pages via a GitHub Actions workflow.</p>"
            "<p>Check out the <a href='about.html'>About</a> page to learn more.</p>"
        ),
    },
    {
        "filename": "about.html",
        "title": "About",
        "heading": "About This Project",
        "content": (
            "<p>This is a test repository for GitHub Pages. "
            "Static HTML pages are generated by Python scripts and deployed "
            "automatically via a GitHub Actions workflow on every push to <code>main</code>.</p>"
            "<p><a href='index.html'>&larr; Back to Home</a></p>"
        ),
    },
]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title} – GithubPagesTest</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      color: #333;
      line-height: 1.6;
    }}
    nav a {{ margin-right: 1em; }}
    footer {{ margin-top: 40px; font-size: 0.85em; color: #888; }}
  </style>
</head>
<body>
  <nav>
    <a href="index.html">Home</a>
    <a href="about.html">About</a>
  </nav>
  <hr />
  <h1>{heading}</h1>
  {content}
  <footer>
    <p>Generated on {generated_at} by <code>scripts/generate_pages.py</code></p>
  </footer>
</body>
</html>
"""


def generate_site(output_dir: str = OUTPUT_DIR) -> None:
    """Generate all HTML pages into *output_dir*."""
    os.makedirs(output_dir, exist_ok=True)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    for page in PAGES:
        html = HTML_TEMPLATE.format(
            title=page["title"],
            heading=page["heading"],
            content=page["content"],
            generated_at=generated_at,
        )
        output_path = os.path.join(output_dir, page["filename"])
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"Generated: {output_path}")

    print(f"\nSite generation complete. {len(PAGES)} page(s) written to '{output_dir}/'.")


if __name__ == "__main__":
    generate_site()
