PAGES = [
    # Previous entries...
    {"filename": "hello-world.html", "title": "Hello World", "heading": "Hello World Page", "content": "<img src=\"_site/hello_world.png\" alt=\"Hello World Image\" />\n    <p>This page displays the Hello World image, generated dynamically by the script hello_world_image.py.</p>"},
    # Other entries...
]